title: Malawi HIV Maps
email: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://henryspatialanalysis.github.io/mwi-hiv-maps-staging/"

collections:
  districts:
    output: true
    permalink: /:title.html
  district_maps:
    output: true
    permalink: /maps/:title/index.html
  prevalence_maps:
    output: true
    permalink: /prevalence/:title/index.html
  vls_maps:
    output: true
    permalink: /vls/:title/index.html

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing:
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
